spring:
  datasource:
    username: codelex
    password: codelex
    url: jdbc:postgresql://localhost:5432/student_system
  jpa:
    hibernate:
      ddl-auto: create
  liquibase:
    change-log: classpath:/liquibase/updates.xml
    enabled: true
student_system:
  store-type: database

